
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cunoc.JFlex_Cup.Java;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int C_APERTURA = 64;
  public static final int SHORT = 3;
  public static final int Y = 58;
  public static final int DOBLE_PUNTO = 20;
  public static final int CHAR = 9;
  public static final int L_CIERRE = 63;
  public static final int EXNTENDS = 24;
  public static final int ENTERO = 46;
  public static final int O = 59;
  public static final int CASE = 37;
  public static final int RESTA = 51;
  public static final int DOUBLE = 8;
  public static final int PRIVATE = 40;
  public static final int INT = 4;
  public static final int FOR = 31;
  public static final int F = 7;
  public static final int STATIC = 44;
  public static final int SIMPLE_COMILLA = 19;
  public static final int IGUAL = 54;
  public static final int CARACTER = 10;
  public static final int CLASS = 22;
  public static final int C_CIERRE = 65;
  public static final int SUMA = 50;
  public static final int IF = 34;
  public static final int P_CIERRE = 61;
  public static final int MAYOR_Q = 57;
  public static final int THIS = 23;
  public static final int ID = 47;
  public static final int PUNTO_COMA = 18;
  public static final int DECIMAL = 45;
  public static final int EOF = 0;
  public static final int BOOLEAN = 12;
  public static final int RETURN = 39;
  public static final int MENOR_Q = 56;
  public static final int TRUE = 13;
  public static final int SUPER = 26;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int COMA = 21;
  public static final int MODULO = 55;
  public static final int TRY = 29;
  public static final int BREAK = 38;
  public static final int VOID = 28;
  public static final int SWITCH = 36;
  public static final int BYTE = 2;
  public static final int IMPORT = 16;
  public static final int ELSE = 35;
  public static final int PROTECTED = 42;
  public static final int PUNTO = 17;
  public static final int P_APERTURA = 60;
  public static final int PACKAGE = 15;
  public static final int FINAL = 43;
  public static final int WHILE = 32;
  public static final int PUBLIC = 41;
  public static final int FLOAT = 6;
  public static final int CHARTN = 11;
  public static final int LONG = 5;
  public static final int STRING = 48;
  public static final int L_APERTURA = 62;
  public static final int TEXT = 49;
  public static final int FALSE = 14;
  public static final int DIVISION = 53;
  public static final int IMPLEMENTS = 25;
  public static final int DO = 33;
  public static final int MULTIPLICACION = 52;
  public static final int CATCH = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BYTE",
  "SHORT",
  "INT",
  "LONG",
  "FLOAT",
  "F",
  "DOUBLE",
  "CHAR",
  "CARACTER",
  "CHARTN",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "PACKAGE",
  "IMPORT",
  "PUNTO",
  "PUNTO_COMA",
  "SIMPLE_COMILLA",
  "DOBLE_PUNTO",
  "COMA",
  "CLASS",
  "THIS",
  "EXNTENDS",
  "IMPLEMENTS",
  "SUPER",
  "NEW",
  "VOID",
  "TRY",
  "CATCH",
  "FOR",
  "WHILE",
  "DO",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "BREAK",
  "RETURN",
  "PRIVATE",
  "PUBLIC",
  "PROTECTED",
  "FINAL",
  "STATIC",
  "DECIMAL",
  "ENTERO",
  "ID",
  "STRING",
  "TEXT",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "IGUAL",
  "MODULO",
  "MENOR_Q",
  "MAYOR_Q",
  "Y",
  "O",
  "P_APERTURA",
  "P_CIERRE",
  "L_APERTURA",
  "L_CIERRE",
  "C_APERTURA",
  "C_CIERRE"
  };
}

