
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cunoc.JFlex_Cup.Java;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ONEO = 74;
  public static final int SHORT = 3;
  public static final int MENOR_Q = 71;
  public static final int L_APERTURA = 78;
  public static final int DIVISION = 63;
  public static final int SIMPLE_COMILLA = 21;
  public static final int CHARTN = 11;
  public static final int IMPLEMENTS = 27;
  public static final int MODULO_IGUAL = 61;
  public static final int P_APERTURA = 76;
  public static final int TWOY = 67;
  public static final int CATCH = 32;
  public static final int CREMENTO = 55;
  public static final int TWOO = 66;
  public static final int DOBLE_PUNTO = 22;
  public static final int C_APERTURA = 80;
  public static final int DOUBLE = 8;
  public static final int PROTECTED = 45;
  public static final int FALSE = 14;
  public static final int TEXT = 52;
  public static final int MAYOR_Q = 72;
  public static final int FINAL = 46;
  public static final int FLOAT = 6;
  public static final int PACKAGE = 17;
  public static final int SUMA_IGUAL = 53;
  public static final int PUNTO_COMA = 20;
  public static final int CLASS = 24;
  public static final int INCREMENTO = 56;
  public static final int COMA = 23;
  public static final int SUPER = 28;
  public static final int ENTERO = 49;
  public static final int MODULO = 65;
  public static final int TRUE = 13;
  public static final int LONG = 5;
  public static final int IGUAL = 64;
  public static final int WHILE = 34;
  public static final int DECIMAL = 48;
  public static final int CHAR = 9;
  public static final int BOOLEAN = 12;
  public static final int SWITCH = 38;
  public static final int DO = 35;
  public static final int FOR = 33;
  public static final int VOID = 30;
  public static final int PUBLIC = 44;
  public static final int RETURN = 42;
  public static final int ELSE = 37;
  public static final int TRY = 31;
  public static final int C_CIERRE = 81;
  public static final int BREAK = 41;
  public static final int MENOR_Q_IGUAL = 69;
  public static final int INT = 4;
  public static final int P_CIERRE = 77;
  public static final int F = 7;
  public static final int EOF = 0;
  public static final int PUNTO = 19;
  public static final int THIS = 25;
  public static final int DEFAULT = 40;
  public static final int SUMA = 54;
  public static final int RESTA_IGUAL = 57;
  public static final int ADMIRACION_IGUAL = 75;
  public static final int CARACTER = 10;
  public static final int IMPORT = 18;
  public static final int EXNTENDS = 26;
  public static final int error = 1;
  public static final int DOUBLE_IGUAL = 68;
  public static final int RESTA = 58;
  public static final int IF = 36;
  public static final int ID = 50;
  public static final int MULTIPLICACION_IGUAL = 59;
  public static final int L_CIERRE = 79;
  public static final int MULTIPLICACION = 60;
  public static final int CASE = 39;
  public static final int NEW = 29;
  public static final int STRING = 51;
  public static final int BYTE = 2;
  public static final int DIVISION_IGUAL = 62;
  public static final int MAYOR_Q_IGUAL = 70;
  public static final int PRIVATE = 43;
  public static final int ONEY = 73;
  public static final int ADMIRACION = 15;
  public static final int STATIC = 47;
  public static final int INTERO = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BYTE",
  "SHORT",
  "INT",
  "LONG",
  "FLOAT",
  "F",
  "DOUBLE",
  "CHAR",
  "CARACTER",
  "CHARTN",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "ADMIRACION",
  "INTERO",
  "PACKAGE",
  "IMPORT",
  "PUNTO",
  "PUNTO_COMA",
  "SIMPLE_COMILLA",
  "DOBLE_PUNTO",
  "COMA",
  "CLASS",
  "THIS",
  "EXNTENDS",
  "IMPLEMENTS",
  "SUPER",
  "NEW",
  "VOID",
  "TRY",
  "CATCH",
  "FOR",
  "WHILE",
  "DO",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "RETURN",
  "PRIVATE",
  "PUBLIC",
  "PROTECTED",
  "FINAL",
  "STATIC",
  "DECIMAL",
  "ENTERO",
  "ID",
  "STRING",
  "TEXT",
  "SUMA_IGUAL",
  "SUMA",
  "CREMENTO",
  "INCREMENTO",
  "RESTA_IGUAL",
  "RESTA",
  "MULTIPLICACION_IGUAL",
  "MULTIPLICACION",
  "MODULO_IGUAL",
  "DIVISION_IGUAL",
  "DIVISION",
  "IGUAL",
  "MODULO",
  "TWOO",
  "TWOY",
  "DOUBLE_IGUAL",
  "MENOR_Q_IGUAL",
  "MAYOR_Q_IGUAL",
  "MENOR_Q",
  "MAYOR_Q",
  "ONEY",
  "ONEO",
  "ADMIRACION_IGUAL",
  "P_APERTURA",
  "P_CIERRE",
  "L_APERTURA",
  "L_CIERRE",
  "C_APERTURA",
  "C_CIERRE"
  };
}

