
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cunoc.JFlex_Cup.HTML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int C_APERTURA = 35;
  public static final int FINAL_HTML = 7;
  public static final int FINAL_TR = 13;
  public static final int DOBLE_PUNTO = 39;
  public static final int L_CIERRE = 34;
  public static final int INICIO_TR = 12;
  public static final int COMMENT = 28;
  public static final int METHODS = 29;
  public static final int FINAL_TH = 15;
  public static final int RESTA = 3;
  public static final int INTEGER = 24;
  public static final int FINAL_TD = 17;
  public static final int INICIO_TH = 14;
  public static final int INICIO_HTML = 6;
  public static final int INICIO_TD = 16;
  public static final int SIMPLE_COMILLA = 37;
  public static final int INICIO_H = 8;
  public static final int C_CIERRE = 36;
  public static final int NUM = 23;
  public static final int SUMA = 2;
  public static final int P_CIERRE = 32;
  public static final int PUNTO_COMA = 38;
  public static final int ID = 22;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 20;
  public static final int FINAL_H = 9;
  public static final int INICIO_TAB = 10;
  public static final int PUNTO = 40;
  public static final int P_APERTURA = 31;
  public static final int VARIABLE = 30;
  public static final int FINAL_TAB = 11;
  public static final int STRING = 25;
  public static final int TEXT = 21;
  public static final int L_APERTURA = 33;
  public static final int USER = 26;
  public static final int DIVISION = 5;
  public static final int FINAL_BR = 19;
  public static final int RESULT = 27;
  public static final int MULTIPLICACION = 4;
  public static final int INICIO_BR = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "INICIO_HTML",
  "FINAL_HTML",
  "INICIO_H",
  "FINAL_H",
  "INICIO_TAB",
  "FINAL_TAB",
  "INICIO_TR",
  "FINAL_TR",
  "INICIO_TH",
  "FINAL_TH",
  "INICIO_TD",
  "FINAL_TD",
  "INICIO_BR",
  "FINAL_BR",
  "COMA",
  "TEXT",
  "ID",
  "NUM",
  "INTEGER",
  "STRING",
  "USER",
  "RESULT",
  "COMMENT",
  "METHODS",
  "VARIABLE",
  "P_APERTURA",
  "P_CIERRE",
  "L_APERTURA",
  "L_CIERRE",
  "C_APERTURA",
  "C_CIERRE",
  "SIMPLE_COMILLA",
  "PUNTO_COMA",
  "DOBLE_PUNTO",
  "PUNTO"
  };
}

